<?php

define("JAZZCASH_MERCHANT_ID", "YOUR_MERCHANT_ID");
define("JAZZCASH_PASSWORD", "YOUR_PASSWORD");
define("JAZZCASH_INTEGRITY_SALT", "YOUR_INTEGRITY_SALT");

define(
    "JAZZCASH_ENDPOINT",
    "YOUR_SANDBOX_ENDPOINT"
);